#!/usr/bin/env php
<?php

require 'Libs/markdown.php';

$configs = array(
	'source-dir' => 'Source',
	'output-dir' => 'Output',
	'files' => array(
		'Entity/Entity.md'
	),
	'copy' => array(
		'HTML/Static/museo500-regular-webfont.eot' => 'museo500-regular-webfont.eot',
		'HTML/Static/museo500-regular-webfont.svg' => 'museo500-regular-webfont.svg',
		'HTML/Static/museo500-regular-webfont.ttf' => 'museo500-regular-webfont.ttf',
		'HTML/Static/museo500-regular-webfont.woff' => 'museo500-regular-webfont.woff',
		'HTML/Static/styles.css' => 'styles.css',
	)
);

for ($i = 1; $i < $_SERVER['argc']; $i += 2) {
	$argv = $_SERVER['argv'][$i + 1];
	$argn = $_SERVER['argv'][$i];
	$argn = preg_replace('/^--/', '', $argn);
	if (isset($configs[$argn])) $configs[$argn] = $argv;
}

foreach ($configs['files'] as $file) {

	$source_path = $configs['source-dir'] . '/' . $file;
	$output_path = $configs['output-dir'] . '/' . $file;
	$output_path = preg_replace('/\.md$/', '.html', $output_path);
	$output_dir  = dirname($output_path);

	$source = file_get_contents($source_path);
	$source = markdown($source);

	ob_start();
	include 'Template/HTML/Class.template.php';
	$output = ob_get_contents();
	ob_end_clean();

	@mkdir($output_dir, 0755, true);

	file_put_contents($output_path, $output);
}


foreach ($configs['copy'] as $from => $to) {
	@copy('Template/' . $from, $configs['output-dir'] . '/' . $to);
}

