#!/usr/bin/env php
<?php

require 'Libs/markdown.php';

$configs = array(
	'source-dir' => 'Source',
	'output-dir' => 'Output',
	'files' => array(
		'Component/Component.md',
		'Control/Alert.md',
		'Control/ActivityIndicator.md',
		'Control/BarButtonGroup.md',
		'Control/BarButton.md',
		'Control/ButtonGroup.md',
		'Control/Button.md',
		'Control/Image.md',
		'Control/NavigationBar.md',
		'Control/Slider.md',
		'Control/List.md',
		'Control/NavigationBarItem.md',
		'Control/Text.md',
		'Control/Bar.md',
		'Control/BarItem.md',
		'Control/Control.md',
		'Control/ListItem.md',
		'Control/Overlay.md',
		'Element/Element.From.md',
		'Element/Element.md',
		'Entity/Entity.md',
		'Scroller/Scroller.Engine.IScroll.md',
		'Scroller/Scroller.Engine.Native.md',
		'Scroller/Scroller.Engine.md',
		'Scroller/Scroller.md',
		'View/ScrollView.md',
		'View/View.md',
		'View/ViewContent.md',
		'View/ViewPanel.md',
		'View/ViewPanelContent.md',
		'View/ViewStack.md',
		'View/ViewStackContent.md',
		'ViewController/ViewController.md',
		'ViewController/ViewControllerPanel.md',
		'ViewController/ViewControllerStack.Navigation.md',
		'ViewController/ViewControllerStack.md',
		'ViewTransition/ViewTransition.Cover.Box.md',
		'ViewTransition/ViewTransition.Cover.md',
		'ViewTransition/ViewTransition.Fade.md',
		'ViewTransition/ViewTransition.None.md',
		'ViewTransition/ViewTransition.md',
		'ViewTransition/ViewTransition.Cover.Page.md',
		'ViewTransition/ViewTransition.Cubic.md',
		'ViewTransition/ViewTransition.Flip.md',
		'ViewTransition/ViewTransition.Slide.md',
		'Window/Window.md',
		'Window/WindowContent.md',
		'Window/WindowController.md',
	),
	'copy' => array(
		'HTML/Static/museo500-regular-webfont.eot' => 'museo500-regular-webfont.eot',
		'HTML/Static/museo500-regular-webfont.svg' => 'museo500-regular-webfont.svg',
		'HTML/Static/museo500-regular-webfont.ttf' => 'museo500-regular-webfont.ttf',
		'HTML/Static/museo500-regular-webfont.woff' => 'museo500-regular-webfont.woff',
		'HTML/Static/styles.css' => 'styles.css',
	)
);

for ($i = 1; $i < $_SERVER['argc']; $i += 2) {
	$argv = $_SERVER['argv'][$i + 1];
	$argn = $_SERVER['argv'][$i];
	$argn = preg_replace('/^--/', '', $argn);
	if (isset($configs[$argn])) $configs[$argn] = $argv;
}

foreach ($configs['files'] as $file) {

	$source_path = $configs['source-dir'] . '/' . $file;
	$output_path = $configs['output-dir'] . '/' . $file;
	$output_path = preg_replace('/\.md$/', '.html', $output_path);
	$output_dir  = dirname($output_path);

	$source = file_get_contents($source_path);
	$source = markdown($source);

	ob_start();
	include 'Template/HTML/Class.template.php';
	$output = ob_get_contents();
	ob_end_clean();

	@mkdir($output_dir, 0755, true);

	file_put_contents($output_path, $output);
}


foreach ($configs['copy'] as $from => $to) {
	@copy('Template/' . $from, $configs['output-dir'] . '/' . $to);
}

